# Generated by Django 4.2.9 on 2024-02-03 20:11

import MyPlants.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=20,
                        validators=[MyPlants.core.validators.capital_letter_validator],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=20,
                        validators=[MyPlants.core.validators.capital_letter_validator],
                    ),
                ),
                ("profile_picture", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
