# Generated by Django 4.2.9 on 2024-02-03 20:11

import MyPlants.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plant_type",
                    models.CharField(
                        choices=[
                            ("Outdoor Plants", "Outdoor Plants"),
                            ("Indoor Plants", "Indoor Plants"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            MyPlants.core.validators.only_letter_validator,
                        ],
                    ),
                ),
                ("image", models.URLField()),
                ("description", models.TextField()),
                ("price", models.FloatField()),
            ],
        ),
    ]
